apiVersion: v1
kind: Service
metadata:
  name: es-cluster-svc
  namespace: {{ .Values.global.namespace }}
  labels:
    name: es
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      name: es-single1
      nodePort: {{ .Values.elasticsearch.elastic1NodePort }}
    - port: 9300
      targetPort: 9300
      name: es-single2
      nodePort: {{ .Values.elasticsearch.elastic2NodePort }}
  selector:
    name: es