apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: http-grafana
{{- if eq .Values.grafana.serviceType "NodePort" }}
    nodePort: {{ .Values.grafana.nodePort }}
{{- end }}
  selector:
    app: grafana
  type: {{ .Values.grafana.serviceType }}