apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: es-kibana
  name: es-kibana
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-kibana
  template:
    metadata:
      labels:
        app: es-kibana
    spec:
      containers:
      - image: {{ .Values.global.registry }}/{{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag}}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        name: kibana
        volumeMounts:
        - name: kibana-config
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
        resources:
{{ toYaml .Values.kibana.resources | indent 10 }}          
      volumes:
      - name: kibana-config
        configMap:
          name: kibana-config
