apiVersion: v1
data:
  config-file.yaml: |
    driver: "elasticsearch"
    mysqloptions:
      host: "sqlhost"
    esoptions:
      endpoint: "http://es-cluster-svc.{{ .Values.global.namespace }}:9200"
      username: {{ .Values.global.esUser }}
      password: {{ .Values.global.esPassword }}
kind: ConfigMap
metadata:
  name: grafanadi-cm
  namespace: {{ .Values.global.namespace }}
