apiVersion: v1
kind: Service
metadata:
  name: grafanadi
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: common-port
    port: 8080
    protocol: TCP
    targetPort: http-grafanadi
    {{- if eq .Values.grafanadiType "NodePort" }}
    nodePort: {{ .Values.grafanadiNodePort }}
    {{- end }}
  - name: auth-port
    port: 8081
    protocol: TCP
    targetPort: http-auth
    {{- if eq .Values.grafanadiType "NodePort" }}
    nodePort: {{ .Values.grafanadiAuthNodePort }}
    {{- end }}
  selector:
    app: grafanadi
  type: {{ .Values.grafanadiType }}