apiVersion: v1
kind: Service
metadata:
  name: grafanadi
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: http-grafanadi
{{- if eq .Values.grafanadi.serviceType "NodePort" }}
    nodePort: {{ .Values.grafanadi.nodePort }}
{{- end }}
  selector:
    app: grafanadi
  type: {{ .Values.grafanadi.serviceType }}