apiVersion: v1
kind: Service
metadata:
  name: grafanadi
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http-grafanadi
    targetPort: http-grafanadi
{{- if eq .Values.grafanadiType "NodePort" }}
    nodePort: {{ .Values.grafanadiNodePort }}
{{- end }}
  - port: 8089
    name: http-restapi
    protocol: TCP
    targetPort: http-restapi
{{- if eq .Values.grafanadiType "NodePort" }}
    nodePort: {{ .Values.restapiNodePort }}
{{- end }}
  selector:
    app: grafanadi
  type: {{ .Values.grafanadiType }}