services:
  grafana:
    user: root
    container_name: 'antgroup-tkptable-panel'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.3.3}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3005:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/antgroup-tkptable-panel
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/antgroup-tkptable-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.antgroup-tkptable-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: antgroup-tkptable-panel
