{{- if .Values.auditApierver.enableAuditApiserver }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: apiserver-audit-installer
  namespace: {{ .Values.global.namespace }}
  labels:
    k8s-app: apiserver-audit-installer
spec:
  selector:
    matchLabels:
      name: apiserver-audit-installer
  template:
    metadata:
      labels:
        name: apiserver-audit-installer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - master
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: audit-config-installer
        image: {{ .Values.global.registry }}/{{ .Values.lunettes.image.repository }}:{{ .Values.lunettes.image.tag}}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command:
        - /auditinstaller
        env:
        - name: NAMESPACE
          value: {{ .Values.global.namespace }}
        - name: AUDIT_LOG_MAX_AGE
          value: "{{ .Values.auditApierver.auditLogMaxAge }}"
        - name: AUDIT_LOG_MAX_BACKUP
          value: "{{ .Values.auditApierver.auditLogMaxBackup }}"
        - name: AUDIT_LOG_MAX_SIZE
          value: "{{ .Values.auditApierver.auditLogMaxSize }}"
        resources:
{{ toYaml .Values.auditApierver.resources | indent 10 }}
        volumeMounts:
        - name: rootdir
          mountPath: /node/root
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rootdir
        hostPath:
          path: /
{{- end }}          