{{- if .Values.auditApierver.enableAuditApiserver }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.global.namespace }}
  name: audit-configmap-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
{{- end }}

---
{{- if .Values.auditApierver.enableAuditApiserver }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: audit-configmap-reader
  namespace: {{ .Values.global.namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: audit-configmap-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}