apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: {{ .Values.global.namespace }}
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        image: {{ .Values.global.registry }}/{{ .Values.jaeger.image.repository }}:{{ .Values.jaeger.image.tag}}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        name: jaeger
        resources: 
{{ toYaml .Values.jaeger.resources | indent 10 }}        