apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lunettes-reader
  namespace: {{ .Values.global.namespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lunettes-reader-binding
  namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lunettes-reader
subjects:
- kind: ServiceAccount
  name: lunettes-sa
  namespace: {{ .Values.global.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lunettes-sa
  namespace: {{ .Values.global.namespace }}