apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.global.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 15s
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'lunettes'
      metrics_path: '/metrics'
      scrape_interval: 10s
      static_configs:
      - targets: ['{{ template "lunettes.fullname" . }}.lunettes:8080']