name: 'Image Transfer'
on:
  push:
    branches:
    - main
    paths:
    - 'hack/images-transfer/**'
  workflow_dispatch:

env:
  ACR_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  DOCKERHUB_REGISTRY: docker.io
  TARGET_NAMESPACE: lunettes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # git checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # 登录 acr https://cr.console.aliyun.com/cn-hangzhou/instance/repositories
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}

      # 登录 dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        working-directory: ./hack/images-transfer
        run: |
          chmod +x images-transfer.sh
          ./images-transfer.sh ${{ env.ACR_REGISTRY }}/${{ env.TARGET_NAMESPACE }}
          ./images-transfer.sh ${{ env.DOCKERHUB_REGISTRY }}/${{ env.TARGET_NAMESPACE }}
